name: Trigger auto deployment for weather-yatri-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/weather-yatri-container-app-AutoDeployTrigger-d32a2279-f1f1-415e-861c-96db7be5017e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEATHERYATRICONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEATHERYATRICONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEATHERYATRICONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.WEATHERYATRICONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEATHERYATRICONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: weather-yatri-container-app
          resourceGroup: weather-yatri-rg
          imageToBuild: yatricloud/weather-yatri-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


